[build]
  base = "frontend"            # Points to the frontend directory
  publish = "dist"             # Directory to publish after building the frontend
  command = "npm run build"    # Command to build your frontend

[functions]
  directory = "backend/functions"  # Directory for backend serverless functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200